dist: bionic
language: python
python: 3.8

services:
  - docker

env:
  global:
    - POSTGRES_DB=accidents
    - POSTGRES_USER=ci
    - POSTGRES_PASSWORD=ci

install: pip install -r requirements-dev.txt
script:
  - isort --check-only src scripts
  - mypy --package=src
  - flake8 src/ scripts/
  - docker-compose build
