tables = {
    "accident": "accidents",
    "vehicle": "vehicles",
    "person": "persons",
    "pbtype": "non_motorists",  # From 2014.
    "distract": "distractions",
    "drimpair": "impairments",
    "factor": "veh_factors",
    "vision": "visual_obstructions",
    "nmimpair": "nm_impairments",
}

table_columns = {
    "accidents": [
        "st_case",
        "year",
        "month",
        "day",
        "hour",
        "minute",
        "latitude",
        "longitud",
        "lgt_cond",
        "weather1",
        "weather2",
    ],
    "vehicles": [
        "st_case",
        "veh_no",
        "hit_run",
        "pfire",
        "dr_drink",
        "l_status",
    ],
    "persons": [
        "st_case",
        "veh_no",
        "per_no",
        "age",
        "sex",
        "per_typ",
        "drinking",
        "alc_res",
        "drugs",
        "death_da",
    ],
    "non_motorists": [
        "st_case",
        "veh_no",
        "per_no",
        "pbcwalk",
        "pbswalk",
        "pbszone",
        "pedcgp",
        "bikecgp",
    ],
    "distractions": [
        "st_case",
        "veh_no",
        "mdrdstrd",
    ],
    "impairments": [
        "st_case",
        "veh_no",
        "drimpair",
    ],
    "veh_factors": [
        "st_case",
        "veh_no",
        "mfactor",
    ],
    "visual_obstructions": [
        "st_case",
        "veh_no",
        "mvisobsc",
    ],
    "nm_impairments": [
        "st_case",
        "veh_no",
        "per_no",
        "nmimpair",
    ],
}
