on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: accidents
      POSTGRES_USER: ci
      POSTGRES_PASSWORD: ci

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Lint
      run: |
        isort --check-only src scripts
        flake8 src/ scripts/
    - name: Typecheck
      run: mypy --package=src
    - name: Build stack
      run: docker-compose build
